-- MySQL Script generated by MySQL Workbench
-- Fri Sep 11 23:36:09 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema cane_ki_database
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cane_ki_database
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cane_ki_database` DEFAULT CHARACTER SET utf8 ;
USE `cane_ki_database` ;

-- -----------------------------------------------------
-- Table `cane_ki_database`.`farmers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cane_ki_database`.`farmers` (
  `farmer_id` VARCHAR(20) NOT NULL,
  `id_card` VARCHAR(13) NOT NULL,
  `full_name` VARCHAR(100) NOT NULL,
  `phone_number` VARCHAR(15) NULL DEFAULT NULL,
  `address` TEXT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`farmer_id`),
  UNIQUE INDEX `id_card` (`id_card` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cane_ki_database`.`cane_plots`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cane_ki_database`.`cane_plots` (
  `plot_id` VARCHAR(20) NOT NULL,
  `farmer_id` VARCHAR(20) NOT NULL,
  `plot_name` VARCHAR(100) NOT NULL,
  `sub_district` VARCHAR(50) NULL DEFAULT NULL,
  `district` VARCHAR(50) NULL DEFAULT NULL,
  `province` VARCHAR(50) NULL DEFAULT 'สุรินทร์',
  `total_rai` DECIMAL(8,2) NOT NULL,
  `cane_variety` VARCHAR(50) NULL DEFAULT NULL,
  `planting_date` DATE NULL DEFAULT NULL,
  `boundary_geojson` JSON NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`plot_id`),
  INDEX `farmer_id` (`farmer_id` ASC) VISIBLE,
  CONSTRAINT `cane_plots_ibfk_1`
    FOREIGN KEY (`farmer_id`)
    REFERENCES `cane_ki_database`.`farmers` (`farmer_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cane_ki_database`.`cane_deliveries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cane_ki_database`.`cane_deliveries` (
  `delivery_id` VARCHAR(20) NOT NULL,
  `plot_id` VARCHAR(20) NOT NULL,
  `delivery_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `license_plate` VARCHAR(20) NULL DEFAULT NULL,
  `gross_weight_kg` DECIMAL(10,2) NOT NULL,
  `tare_weight_kg` DECIMAL(10,2) NOT NULL,
  `net_weight_ton` DECIMAL(10,2) GENERATED ALWAYS AS (((`gross_weight_kg` - `tare_weight_kg`) / 1000.0)) STORED,
  `ccs` DECIMAL(4,2) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`delivery_id`),
  INDEX `plot_id` (`plot_id` ASC) VISIBLE,
  CONSTRAINT `cane_deliveries_ibfk_1`
    FOREIGN KEY (`plot_id`)
    REFERENCES `cane_ki_database`.`cane_plots` (`plot_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cane_ki_database`.`satellite_analysis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cane_ki_database`.`satellite_analysis` (
  `analysis_id` INT(11) NOT NULL AUTO_INCREMENT,
  `plot_id` VARCHAR(20) NOT NULL,
  `satellite_source` VARCHAR(50) NULL DEFAULT 'Sentinel-2',
  `capture_date` DATE NOT NULL,
  `mean_ndvi` DECIMAL(4,3) NOT NULL,
  `estimated_yield_per_rai` DECIMAL(6,2) NULL DEFAULT NULL,
  `estimated_total_tons` DECIMAL(10,2) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`analysis_id`),
  INDEX `plot_id` (`plot_id` ASC) VISIBLE,
  CONSTRAINT `satellite_analysis_ibfk_1`
    FOREIGN KEY (`plot_id`)
    REFERENCES `cane_ki_database`.`cane_plots` (`plot_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
